### ISSUE TITLE
Scavenger Hunt Database Expansion

### ISSUE THREAD

**Issue by bfj5889** [TeamGarnet/Garnet-Main-Repo#36]
Not sure if we have this in our schema yet but we will need to have a table that connects points for the scavenger hunts or an expansion on the graves table. 
We can figure it out in the 1/21 meeting.

**Comment by JakeFanelli** [comment]
I added 2 extra attributes to the grave and vegetation tables to include pointValue and hint - changes can be seen in the DB MODEL & SOFTWARE REQs folder under db model.

**Comment by colejohnson** [comment]
That works well, I can design a game system for that.
