### ISSUE TITLE
SQL List Creation

### ISSUE THREAD

**Issue by bfj5889** [TeamGarnet/Garnet-Main-Repo#39]
Leave a link to the document on this issue.
Assign issue to Dervent and another upon completion.

**Comment by JakeFanelli** [comment]
https://drive.google.com/open?id=1LVWBk8d8SfD8ZX9eoRuBnMEde0SsJb8OFCTQ7PA7pIM

**Comment by JakeFanelli** [comment]
Updated document to reflect recent changes to the database.
