### ISSUE TITLE
PHP Unit Testing Software

### ISSUE THREAD

**Issue by bfj5889** [TeamGarnet/Garnet-Main-Repo#40]
Per our Weekly state the solution here. Once complete assign the issue to Dan if configuration is needed.

**Comment by bfj5889** [comment]
Dan has already installed karma so instead you will be researching how to use karma with PHP and then informing Dan if any changes need to be made.
You will probably need to learn how to make a karma basic testing script first.
Quick info that I find in 2min that may help: https://backendcoder.com/php-unit-testing-with-karma-and-jasmine

**Comment by dervent** [comment]
A dummy test using Jasmine framework has been created. Test runs fine locally with Karma. 
**Just a note**: Jasmine and Karma are originally intended for JavaScript testing. Based on my search, PHP testing with these frameworks is very rare and seems awkward. Therefore, I recommend [PHPUnit](https://phpunit.de/index.html) to be used for PHP unit testing. It is widely used and very popular for PHP tests.

**Comment by bfj5889** [comment]
@dervent Go ahead and edit the readme to add PHPUnit in test so that Dan can get it installed into the server. Do this before you start on the php development.

**Comment by dervent** [comment]
Completed Jasmine/Karma and PHPUnit setup along with dummy tests that devs can run locally to verify correct setup of these frameworks (eventually these test should be replaced by actual tests). Added README to get others acquainted with setup and test runs on their local machines.
